import Head from 'next/head'
import Link from 'next/link'
import { useAmp } from 'next/amp'
import Title from '../components/title'
import Card from '../components/card'

export const config = { amp: true }
// export const config = { amp: 'hybrid' }

export default function Cards() {
  const isAmp = useAmp()
  const result = 4 + 5;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx>
        {`
          .imageWrapper {
            align-items: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
          }
          .link {
            color: blue;
            text-decoration: underline;
          }
          amp-img {
            border-radius: 10px;
          }
        `}
      </style>

      <main>
        <div className="imageWrapper">
          <Link href="/">
            <a className="link">Back home!</a>
          </Link>
          <Title>Cards below:</Title>
          <amp-img
            width="100"
            height="100"
            src="https://picsum.photos/100"
            alt="a cool image"
            layout="fixed"
          />
        </div>
        <span>5 + 4 = {result}</span>
        <amp-list
          height="80"
          load-more-bookmark="next"
          load-more="manual"
          src="/api/pokemon"
          width="auto"
        >
          <template type="amp-mustache">
            <Card url="{{url}}" name="{{name}}" />
          </template>
        </amp-list>
        <amp-layout layout="responsive" width="0" height="0"></amp-layout>
      </main>
    </div>
  )
}
