import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Title from '../components/title'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx>
        {`
          .imageWrapper {
            align-items: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
          }
          .link {
            color: blue;
            text-decoration: underline;
          }
        `}
      </style>

      <main>
        <div className="imageWrapper">
          {/* <Link href="/cards">
            <a className="link">To cards!</a>
          </Link> */}
          <Link href="/pokemons">
            <a className="link">To pokemons!</a>
          </Link>
          <Title>AMP Image Test</Title>
        </div>
      </main>
    </div>
  )
}
