import Head from 'next/head'
import Link from 'next/link'
import { useAmp } from 'next/amp'
import Title from '../components/title'
import Button from '../components/button'

export const config = { amp: true }
// export const config = { amp: 'hybrid' }

export async function getStaticProps() {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=5')
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}

export default function Pokemons({ posts }) {
  const isAmp = useAmp()
  
  const handleOnClickButton = () => {
    alert('Clicked');
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx>
        {`
          .main {
            padding: 0 20px;
          }
          .imageWrapper {
            align-items: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
          }
          .link {
            color: blue;
            text-decoration: underline;
          }
          amp-img {
            border-radius: 10px;
          }
          .card {
            border-radius: 3px;
            border: 1px solid grey;
            margin-bottom: 10px;
            padding: 10px;
          }
        `}
      </style>

      <main className="main">
        <div className="imageWrapper">
          <Link href="/">
            <a className="link">Back home!</a>
          </Link>
          <Title>Pokemons (fetched from API) below:</Title>
          <amp-img
            width="100"
            height="100"
            src="https://picsum.photos/100"
            alt="a cool image"
            layout="fixed"
          />
        </div>
        <Button onClick={handleOnClickButton}>Click me</Button>
        {posts?.results?.map(p => {
          return (
            <div className="card" key={p.name}>
              <amp-fit-text width="200" height="80" layout="responsive">
                {p.name}
              </amp-fit-text>
            </div>
          )
        })}
      </main>
    </div>
  )
}
